# https://github.com/zachjs/sv2v

FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends ca-certificates git
RUN apt-get install -y --no-install-recommends curl

RUN curl -sSL https://get.haskellstack.org/ | sh

RUN git clone --depth 1 https://github.com/zachjs/sv2v.git
RUN cd sv2v && make -j$(nproc) && cp bin/sv2v /usr/local/bin

RUN rm -f /usr/local/bin/stack

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

COPY --from=builder /usr/local/bin /usr/local/bin
