# https://github.com/chipsalliance/Surelog

FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git
RUN apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    default-jre \
    python3 \
    python3-orderedmultidict

RUN git clone --depth 1 https://github.com/alainmarcel/Surelog.git
RUN cd Surelog && git submodule update --init --depth 1 --recursive \
 && cmake -B build \
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5 \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
 && cmake --build build -j$(nproc) \
 && cmake --install build --strip

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

COPY --from=builder /usr/local /usr/local
