# https://github.com/chipsalliance/verible

FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git
RUN apt-get install -y --no-install-recommends \
    build-essential \
    curl

RUN curl -fsSL https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 \
    -o /usr/local/bin/bazel && chmod +x /usr/local/bin/bazel

RUN git clone --depth 1 https://github.com/chipsalliance/verible.git
RUN cd verible && bazel build -c opt :install-binaries \
 && .github/bin/simple-install.sh /usr/local/bin

RUN rm -f /usr/local/bin/bazel

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

COPY --from=builder /usr/local /usr/local
