# https://github.com/yosyshq/yosys

FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git
RUN apt-get install -y --no-install-recommends \
    bison \
    build-essential \
    cmake \
    flex \
    gnat \
    python3 \
    zlib1g-dev

RUN git clone --depth 1 https://github.com/ghdl/ghdl
RUN mkdir ghdl/build && cd ghdl/build && ../configure --prefix=/usr/local \
 && make -j$(nproc) && make install

RUN git clone --depth 1 https://github.com/YosysHQ/yosys
RUN cd yosys && git submodule update --init --depth 1 \
 && cmake -B build . -DCMAKE_BUILD_TYPE=Release \
 && cmake --build build --config Release -j$(nproc) \
 && cmake --install build --strip

RUN git clone --depth 1 https://github.com/ghdl/ghdl-yosys-plugin
RUN cd ghdl-yosys-plugin && git submodule update --init --depth 1 \
 && make -j$(nproc) && make install

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

COPY --from=builder /usr/local /usr/local/bin
