# https://github.com/steveicarus/iverilog

FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git
RUN apt-get install -y --no-install-recommends \
    autoconf \
    bison \
    build-essential \
    flex \
    gperf

RUN git clone --depth 1 https://github.com/steveicarus/iverilog
RUN cd iverilog && autoconf && ./configure \
 && make -j$(nproc) && make install

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

COPY --from=builder /usr/local /usr/local

RUN ldconfig
