# https://github.com/chipsalliance/synlig

FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git
RUN apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    default-jre \
    libffi-dev \
    libreadline-dev \
    python3 \
    python3-orderedmultidict \
    tcl-dev
RUN apt-get install -y --no-install-recommends bison flex pkg-config

RUN git clone --depth 1 https://github.com/chipsalliance/synlig
RUN cd synlig \
 && git submodule update --init --depth 1 --recursive third_party/surelog \
 && git submodule update --init --depth 1 --recursive third_party/yosys \
 && find third_party -name "CMakeLists.txt" -exec sed -i -E 's/cmake_minimum_required\s*\([^)]+\)/cmake_minimum_required(VERSION 3.5)/gI' {} + \
 && sed -i '1s/^/#include <cstdint>\n/' third_party/yosys/libs/json11/json11.cpp \
 && make install -j$(nproc)

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

COPY --from=builder /usr/local /usr/local
