FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git
RUN apt-get install -y --no-install-recommends \
    autoconf \
    bison \
    build-essential \
    flex \
    gnat \
    gperf \
    help2man \
    libfl-dev \
    python3 \
    zlib1g-dev

#
# ghdl
#

RUN git clone --depth 1 https://github.com/ghdl/ghdl
RUN mkdir ghdl/build && cd ghdl/build && ../configure --prefix=/usr/local \
 && make -j$(nproc) && make install

#
# iVerilog
#

RUN git clone --depth 1 https://github.com/steveicarus/iverilog
RUN cd iverilog && autoconf && ./configure \
 && make -j$(nproc) && make install

#
# Verilator
#

RUN git clone --depth 1 https://github.com/verilator/verilator
RUN cd verilator && autoconf && ./configure \
 && make -j$(nproc) && make install

#
# cocotb
#

# RUN pip install cocotb --break-system-packages

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

COPY --from=builder /usr/local /usr/local

RUN ldconfig
