# https://github.com/yosyshq/apicula
# https://github.com/YosysHQ/nextpnr

FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq
RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git
RUN apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    libboost-all-dev \
    libeigen3-dev \
    python3-dev

#
# Apicula
#

RUN apt-get install -y --no-install-recommends python3 python3-pip
RUN pip3 install --no-cache-dir --break-system-packages \
    apycula \
    msgpack \
    cattrs

#
# NextPNR
#

RUN git clone --depth 1 https://github.com/YosysHQ/nextpnr
RUN cd nextpnr && git submodule update --init --recursive \
 && mkdir -p build && cd build \
 && cmake .. -DARCH="himbaechel" -DHIMBAECHEL_UARCH="gowin" -DTRELLIS_INSTALL_PREFIX=/usr/local \
 && make -j$(nproc) && make install

#
# Optimization
#

RUN strip /usr/local/bin/* 2>/dev/null || true

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    python3 \
 && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local /usr/local

RUN ldconfig
