FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq

RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git

#
# GHDL (https://github.com/ghdl/ghdl)
#

RUN apt-get install -y --no-install-recommends \
    build-essential \
    gnat \
    zlib1g-dev

RUN git clone --depth 1 https://github.com/ghdl/ghdl
RUN mkdir ghdl/build && cd ghdl/build && ../configure --prefix=/usr/local \
 && make -j$(nproc) && make install

#
# iVerilog (https://github.com/steveicarus/iverilog)
#

RUN apt-get install -y --no-install-recommends \
    autoconf \
    bison \
    build-essential \
    flex \
    gperf

RUN git clone --depth 1 https://github.com/steveicarus/iverilog
RUN cd iverilog && autoconf && ./configure \
 && make -j$(nproc) && make install

#
# Verilator (https://github.com/verilator/verilator)
#

RUN apt-get install -y --no-install-recommends \
    autoconf \
    bison \
    build-essential \
    flex \
    help2man \
    libfl-dev \
    python3

RUN git clone --depth 1 https://github.com/verilator/verilator
RUN cd verilator && autoconf && ./configure \
 && make -j$(nproc) && make install

#
# cocotb
#

RUN apt-get install -y --no-install-recommends \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv

RUN python3 -m venv /opt/venv && /opt/venv/bin/pip install --no-cache-dir cocotb

#
# Optimization
#

RUN strip /usr/local/bin/* 2>/dev/null || true
RUN find /usr/local/lib -name "*.so*" -exec strip --strip-unneeded {} + 2>/dev/null || true

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

ENV PATH="/opt/venv/bin:$PATH"

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    g++ \
    make \
    perl \
    python3 \
    libgnat-14 \
    zlib1g \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local /usr/local
COPY --from=builder /opt/venv /opt/venv

RUN ldconfig
