FROM ubuntu:latest AS builder

WORKDIR /tmp

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qq

RUN apt-get install -y --no-install-recommends \
    ca-certificates \
    git

#
# GHDL (https://github.com/ghdl/ghdl)
#

RUN apt-get install -y --no-install-recommends \
    build-essential \
    gnat \
    zlib1g-dev

RUN git clone --depth 1 https://github.com/ghdl/ghdl
RUN mkdir ghdl/build && cd ghdl/build && ../configure --prefix=/usr/local \
 && make -j$(nproc) && make install

#
# Yosys (https://github.com/yosyshq/yosys)
#

RUN apt-get install -y --no-install-recommends \
    bison \
    build-essential \
    cmake \
    flex \
    python3

RUN git clone --depth 1 https://github.com/YosysHQ/yosys
RUN cd yosys && git submodule update --init --depth 1 \
 && cmake -B build . -DCMAKE_BUILD_TYPE=Release \
 && cmake --build build --config Release -j$(nproc) \
 && cmake --install build --strip

#
# ghdl-yosys-plugin
#

RUN git clone --depth 1 https://github.com/ghdl/ghdl-yosys-plugin
RUN cd ghdl-yosys-plugin && git submodule update --init --depth 1 \
 && make -j$(nproc) && make install

#
# Synlig (https://github.com/chipsalliance/synlig)
#

RUN apt-get install -y --no-install-recommends \
    bison \
    build-essential \
    cmake \
    default-jre \
    flex \
    libffi-dev \
    libreadline-dev \
    pkg-config \
    python3 \
    python3-orderedmultidict \
    tcl-dev

RUN git clone --depth 1 https://github.com/chipsalliance/synlig
RUN cd synlig \
 && git submodule update --init --depth 1 --recursive third_party/surelog \
 && git submodule update --init --depth 1 --recursive third_party/yosys \
 && find third_party -name "CMakeLists.txt" -exec sed -i -E 's/cmake_minimum_required\s*\([^)]+\)/cmake_minimum_required(VERSION 3.5)/gI' {} + \
 && sed -i '1s/^/#include <cstdint>\n/' third_party/yosys/libs/json11/json11.cpp \
 && make install -j$(nproc)

#
# Optimization and clean-up
#

RUN strip /usr/local/bin/* 2>/dev/null || true
RUN find /usr/local/lib -name "*.a" -delete \
 && rm -rf /usr/local/lib/cmake /usr/local/*/pkgconfig

#------------------------------------------------------------------------------

FROM ubuntu:latest AS runtime

RUN apt-get update -qq && apt-get install -y --no-install-recommends \
    libffi-dev \
    tcl-dev \
    libgnat-14 \
    libreadline-dev \
    && rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/bin   /usr/local/bin
COPY --from=builder /usr/local/lib   /usr/local/lib
COPY --from=builder /usr/local/share /usr/local/share

RUN ldconfig
