name: Deploy Docker Images

on:
  push:
  schedule:
    - cron: '0 21 * * 5'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name:
          - synthesis
          - langutils
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker image for ${{ matrix.name }}
      run: docker build -f recipes/${{ matrix.name }} -t ghcr.io/pyfpga/${{ matrix.name }} .
    - name: Push Docker image for ${{ matrix.name }}
      run: docker push ghcr.io/pyfpga/${{ matrix.name }}
